# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'ePrescriptions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ePrescriptions

  pod 'ReSwift'
  pod 'ReSwiftRouter'
  pod 'RxSwift'

end
